import * as XLSX from 'xlsx';
import { formatDate } from './dateUtils';

export const exportToExcel = (user, stats, recentExpenses, recentRevenue, cropStatus) => {
    // Create a new workbook
    const workbook = XLSX.utils.book_new();

    // ========== SUMMARY SHEET ==========
    const summaryData = [
        ['GoreVerse FarmLedger - Farm Report'],
        [],
        ['Generated by:', user?.name || 'User'],
        ['Date:', new Date().toLocaleDateString('en-IN')],
        ['Time:', new Date().toLocaleTimeString('en-IN')],
        [],
        ['=== Financial Summary ==='],
        [],
        ['Metric', 'Amount (₹)'],
        ['Total Revenue', stats.totalRevenue],
        ['Total Expenses', stats.totalExpenses],
        ['Net Profit', stats.netProfit],
        [],
        ['Report Generated:', new Date().toLocaleString('en-IN')]
    ];

    const summarySheet = XLSX.utils.aoa_to_sheet(summaryData);

    // Set column widths
    summarySheet['!cols'] = [
        { wch: 20 },
        { wch: 20 }
    ];

    XLSX.utils.book_append_sheet(workbook, summarySheet, 'Summary');

    // ========== EXPENSES SHEET ==========
    const expensesData = [
        ['Date', 'Category', 'Field/Crop', 'Amount (₹)', 'Payment Method', 'Description']
    ];

    recentExpenses.forEach(exp => {
        expensesData.push([
            formatDate(exp.date),
            exp.category,
            exp.field || 'N/A',
            parseFloat(exp.amount),
            exp.payment_method || '-',
            exp.description || '-'
        ]);
    });

    const expensesSheet = XLSX.utils.aoa_to_sheet(expensesData);
    expensesSheet['!cols'] = [
        { wch: 12 },
        { wch: 15 },
        { wch: 15 },
        { wch: 12 },
        { wch: 15 },
        { wch: 30 }
    ];

    XLSX.utils.book_append_sheet(workbook, expensesSheet, 'Expenses');

    // ========== REVENUE SHEET ==========
    const revenueData = [
        ['Date', 'Source', 'Product/Crop', 'Amount (₹)', 'Payment Status']
    ];

    recentRevenue.forEach(rev => {
        revenueData.push([
            formatDate(rev.date),
            rev.source,
            rev.product || 'N/A',
            parseFloat(rev.amount),
            rev.payment_received ? 'Paid' : 'Pending'
        ]);
    });

    const revenueSheet = XLSX.utils.aoa_to_sheet(revenueData);
    revenueSheet['!cols'] = [
        { wch: 12 },
        { wch: 20 },
        { wch: 20 },
        { wch: 12 },
        { wch: 15 }
    ];

    XLSX.utils.book_append_sheet(workbook, revenueSheet, 'Revenue');

    // ========== CROPS SHEET ==========
    const cropsData = [
        ['Crop Name', 'Field', 'Status', 'Progress (%)', 'Health']
    ];

    cropStatus.forEach(crop => {
        cropsData.push([
            crop.name,
            crop.field,
            crop.status,
            crop.progress,
            crop.health
        ]);
    });

    const cropsSheet = XLSX.utils.aoa_to_sheet(cropsData);
    cropsSheet['!cols'] = [
        { wch: 20 },
        { wch: 20 },
        { wch: 15 },
        { wch: 12 },
        { wch: 15 }
    ];

    XLSX.utils.book_append_sheet(workbook, cropsSheet, 'Crops');

    // Generate filename
    const dateStr = new Date().toLocaleDateString('en-IN').replace(/\//g, '-');
    const timeStr = new Date().toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' }).replace(/:/g, '-');
    const userName = user?.name ? user.name.replace(/\s+/g, '_') : 'User';
    const fileName = `GoreVerse_FarmLedger_Report_${userName}_${dateStr}_${timeStr}.xlsx`;

    // Write and download the file
    XLSX.writeFile(workbook, fileName);
};
