import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { formatDate } from './dateUtils';

export const exportToPDF = (user, stats, recentExpenses, recentRevenue, cropStatus) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();

    // Header with gradient effect (simulated with rectangles)
    doc.setFillColor(15, 23, 42); // Dark blue background
    doc.rect(0, 0, pageWidth, 35, 'F');

    // Logo emoji and title
    doc.setFontSize(24);
    doc.setTextColor(255, 255, 255);
    doc.text('🌱', 14, 15);
    doc.setFontSize(20);
    doc.text('GoreVerse FarmLedger', 25, 20);

    doc.setFontSize(10);
    doc.setTextColor(148, 163, 184); // Gray
    doc.text('Farm Management Report', 25, 28);

    // User info and date
    doc.setFontSize(9);
    doc.setTextColor(203, 213, 225);
    doc.text(`Generated by: ${user?.name || 'User'}`, pageWidth - 14, 15, { align: 'right' });
    doc.text(`Date: ${new Date().toLocaleDateString('en-IN')}`, pageWidth - 14, 21, { align: 'right' });
    doc.text(`Time: ${new Date().toLocaleTimeString('en-IN')}`, pageWidth - 14, 27, { align: 'right' });

    let yPos = 45;

    // Summary Statistics Section
    doc.setFillColor(241, 245, 249); // Light gray background
    doc.rect(0, yPos - 5, pageWidth, 8, 'F');
    doc.setFontSize(14);
    doc.setTextColor(15, 23, 42);
    doc.setFont(undefined, 'bold');
    doc.text('📊 Financial Summary', 14, yPos);
    doc.setFont(undefined, 'normal');

    yPos += 10;

    // Stats boxes
    const boxWidth = (pageWidth - 40) / 3;
    const boxHeight = 22;

    // Revenue Box
    doc.setFillColor(220, 252, 231); // Light green
    doc.roundedRect(14, yPos, boxWidth, boxHeight, 3, 3, 'F');
    doc.setDrawColor(34, 197, 94);
    doc.setLineWidth(0.5);
    doc.roundedRect(14, yPos, boxWidth, boxHeight, 3, 3, 'S');
    doc.setFontSize(9);
    doc.setTextColor(22, 163, 74);
    doc.text('Total Revenue', 14 + boxWidth / 2, yPos + 6, { align: 'center' });
    doc.setFontSize(14);
    doc.setFont(undefined, 'bold');
    doc.setTextColor(20, 83, 45);
    doc.text(`₹${stats.totalRevenue.toLocaleString()}`, 14 + boxWidth / 2, yPos + 15, { align: 'center' });
    doc.setFont(undefined, 'normal');

    // Expenses Box
    doc.setFillColor(254, 226, 226); // Light red
    doc.roundedRect(14 + boxWidth + 5, yPos, boxWidth, boxHeight, 3, 3, 'F');
    doc.setDrawColor(239, 68, 68);
    doc.roundedRect(14 + boxWidth + 5, yPos, boxWidth, boxHeight, 3, 3, 'S');
    doc.setFontSize(9);
    doc.setTextColor(220, 38, 38);
    doc.text('Total Expenses', 14 + boxWidth + 5 + boxWidth / 2, yPos + 6, { align: 'center' });
    doc.setFontSize(14);
    doc.setFont(undefined, 'bold');
    doc.setTextColor(127, 29, 29);
    doc.text(`₹${stats.totalExpenses.toLocaleString()}`, 14 + boxWidth + 5 + boxWidth / 2, yPos + 15, { align: 'center' });
    doc.setFont(undefined, 'normal');

    // Profit Box
    const profitColor = stats.netProfit >= 0 ? [34, 197, 94] : [239, 68, 68];
    doc.setFillColor(profitColor[0], profitColor[1], profitColor[2], 0.1);
    doc.roundedRect(14 + (boxWidth + 5) * 2, yPos, boxWidth, boxHeight, 3, 3, 'F');
    doc.setDrawColor(profitColor[0], profitColor[1], profitColor[2]);
    doc.roundedRect(14 + (boxWidth + 5) * 2, yPos, boxWidth, boxHeight, 3, 3, 'S');
    doc.setFontSize(9);
    doc.setTextColor(profitColor[0], profitColor[1], profitColor[2]);
    doc.text('Net Profit', 14 + (boxWidth + 5) * 2 + boxWidth / 2, yPos + 6, { align: 'center' });
    doc.setFontSize(14);
    doc.setFont(undefined, 'bold');
    doc.text(`₹${stats.netProfit.toLocaleString()}`, 14 + (boxWidth + 5) * 2 + boxWidth / 2, yPos + 15, { align: 'center' });
    doc.setFont(undefined, 'normal');

    yPos += boxHeight + 15;

    // Recent Expenses Table
    doc.setFillColor(241, 245, 249);
    doc.rect(0, yPos - 5, pageWidth, 8, 'F');
    doc.setFontSize(12);
    doc.setTextColor(15, 23, 42);
    doc.setFont(undefined, 'bold');
    doc.text('💸 Recent Expenses', 14, yPos);
    doc.setFont(undefined, 'normal');

    yPos += 5;

    const expenseData = recentExpenses.map(exp => [
        formatDate(exp.date),
        exp.category,
        exp.field || 'N/A',
        `₹${parseFloat(exp.amount).toLocaleString()}`,
        exp.payment_method || '-'
    ]);

    autoTable(doc, {
        startY: yPos,
        head: [['Date', 'Category', 'Field', 'Amount', 'Payment']],
        body: expenseData,
        theme: 'striped',
        headStyles: {
            fillColor: [51, 65, 85],
            textColor: [255, 255, 255],
            fontSize: 9,
            fontStyle: 'bold'
        },
        bodyStyles: {
            fontSize: 8,
            textColor: [51, 65, 85]
        },
        alternateRowStyles: {
            fillColor: [248, 250, 252]
        },
        margin: { left: 14, right: 14 },
        columnStyles: {
            0: { cellWidth: 25 },
            1: { cellWidth: 40 },
            2: { cellWidth: 35 },
            3: { cellWidth: 35, halign: 'right', fontStyle: 'bold' },
            4: { cellWidth: 'auto' }
        }
    });

    yPos = doc.lastAutoTable.finalY + 10;

    // Recent Revenue Table
    doc.setFillColor(241, 245, 249);
    doc.rect(0, yPos - 5, pageWidth, 8, 'F');
    doc.setFontSize(12);
    doc.setTextColor(15, 23, 42);
    doc.setFont(undefined, 'bold');
    doc.text('💰 Recent Revenue', 14, yPos);
    doc.setFont(undefined, 'normal');

    yPos += 5;

    const revenueData = recentRevenue.map(rev => [
        formatDate(rev.date),
        rev.source,
        rev.product || 'N/A',
        `₹${parseFloat(rev.amount).toLocaleString()}`,
        rev.payment_received ? '✓ Paid' : '✗ Pending'
    ]);

    autoTable(doc, {
        startY: yPos,
        head: [['Date', 'Source', 'Product', 'Amount', 'Status']],
        body: revenueData,
        theme: 'striped',
        headStyles: {
            fillColor: [34, 197, 94],
            textColor: [255, 255, 255],
            fontSize: 9,
            fontStyle: 'bold'
        },
        bodyStyles: {
            fontSize: 8,
            textColor: [51, 65, 85]
        },
        alternateRowStyles: {
            fillColor: [248, 250, 252]
        },
        margin: { left: 14, right: 14 },
        columnStyles: {
            0: { cellWidth: 25 },
            1: { cellWidth: 45 },
            2: { cellWidth: 35 },
            3: { cellWidth: 35, halign: 'right', fontStyle: 'bold', textColor: [34, 197, 94] },
            4: { cellWidth: 'auto' }
        }
    });

    yPos = doc.lastAutoTable.finalY + 10;

    // Check if we need a new page
    if (yPos > pageHeight - 60) {
        doc.addPage();
        yPos = 20;
    }

    // Crop Status Table
    doc.setFillColor(241, 245, 249);
    doc.rect(0, yPos - 5, pageWidth, 8, 'F');
    doc.setFontSize(12);
    doc.setTextColor(15, 23, 42);
    doc.setFont(undefined, 'bold');
    doc.text('🌾 Crop Status', 14, yPos);
    doc.setFont(undefined, 'normal');

    yPos += 5;

    const cropData = cropStatus.map(crop => [
        crop.name,
        crop.field,
        crop.status,
        `${crop.progress}%`,
        crop.health
    ]);

    autoTable(doc, {
        startY: yPos,
        head: [['Crop Name', 'Field', 'Status', 'Progress', 'Health']],
        body: cropData,
        theme: 'striped',
        headStyles: {
            fillColor: [168, 85, 247],
            textColor: [255, 255, 255],
            fontSize: 9,
            fontStyle: 'bold'
        },
        bodyStyles: {
            fontSize: 8,
            textColor: [51, 65, 85]
        },
        alternateRowStyles: {
            fillColor: [248, 250, 252]
        },
        margin: { left: 14, right: 14 }
    });

    // Footer
    const finalY = doc.lastAutoTable.finalY || yPos;
    doc.setFillColor(15, 23, 42);
    doc.rect(0, pageHeight - 20, pageWidth, 20, 'F');
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text('Designed & Developed by Abhijit Gore', pageWidth / 2, pageHeight - 10, { align: 'center' });
    doc.setFontSize(7);
    doc.text('GoreVerse FarmLedger - Farm Management System', pageWidth / 2, pageHeight - 5, { align: 'center' });

    // Save the PDF with proper filename
    const dateStr = new Date().toLocaleDateString('en-IN').replace(/\//g, '-');
    const timeStr = new Date().toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' }).replace(/:/g, '-');
    const userName = user?.name ? user.name.replace(/\s+/g, '_') : 'User';
    const fileName = `GoreVerse_FarmLedger_Report_${userName}_${dateStr}_${timeStr}.pdf`;
    doc.save(fileName);
};
